create table if not exists admin_users(user_id uuid primary key references auth.users(id) on delete cascade,display_name text,created_at timestamptz not null default now());
create table if not exists inventory_adjustments(id uuid primary key default gen_random_uuid(),campaign_id uuid not null references campaigns(id) on delete cascade,prize_id uuid not null references prizes(id),admin_user_id uuid not null references auth.users(id),delta int not null check(delta<>0),reason text not null check(char_length(trim(reason)) between 3 and 300),created_at timestamptz not null default now());
alter table admin_users enable row level security;alter table inventory_adjustments enable row level security;revoke all on admin_users,inventory_adjustments from anon,authenticated;

create or replace function admin_dashboard(p_campaign text) returns jsonb language sql security definer set search_path=public as $$
with c as(select id,code,name,status,total_inventory from campaigns where code=p_campaign),ps as(select p.id,p.code,p.name,p.display_order,p.total_qty,count(pu.id)::int units,count(*)filter(where pu.status='AVAILABLE')::int available,count(*)filter(where pu.status='AWARDED')::int awarded,count(*)filter(where pu.status='CLAIMED')::int claimed from prizes p join c on c.id=p.campaign_id left join prize_units pu on pu.prize_id=p.id group by p.id,p.code,p.name,p.display_order,p.total_qty order by p.display_order),t as(select count(*)::int spins,count(*)filter(where s.status='CLAIMED')::int claimed,count(*)filter(where s.status='AWARDED')::int unclaimed from spins s join c on c.id=s.campaign_id)
select jsonb_build_object('campaign',(select to_jsonb(c)from c),'totals',(select to_jsonb(t)from t),'inventory',coalesce((select jsonb_agg(to_jsonb(ps))from ps),'[]'::jsonb),'recent_adjustments',coalesce((select jsonb_agg(x)from(select ia.id,ia.delta,ia.reason,ia.created_at,p.code prize_code,p.name prize_name,coalesce(au.display_name,ia.admin_user_id::text)admin_name from inventory_adjustments ia join c on c.id=ia.campaign_id join prizes p on p.id=ia.prize_id left join admin_users au on au.user_id=ia.admin_user_id order by ia.created_at desc limit 20)x),'[]'::jsonb));$$;

create or replace function admin_list_spins(p_campaign text,p_search text default '',p_page int default 1,p_page_size int default 25) returns jsonb language plpgsql security definer set search_path=public as $$declare r jsonb;pg int:=greatest(p_page,1);sz int:=least(greatest(p_page_size,1),100);begin with f as(select s.id,s.created_at,s.status,s.claimed_at,s.claim_web_url,s.sheet_sync_status,pt.name participant_name,pt.phone,p.name prize_name,p.code prize_code from spins s join campaigns c on c.id=s.campaign_id join participants pt on pt.id=s.participant_id join prizes p on p.id=s.prize_id where c.code=p_campaign and(trim(coalesce(p_search,''))=''or pt.name ilike '%'||trim(p_search)||'%'or pt.phone ilike '%'||trim(p_search)||'%')),rows as(select * from f order by created_at desc offset((pg-1)*sz)limit sz)select jsonb_build_object('items',coalesce((select jsonb_agg(to_jsonb(rows))from rows),'[]'::jsonb),'total',(select count(*)from f),'page',pg,'page_size',sz)into r;return r;end$$;

create or replace function admin_adjust_inventory(p_campaign text,p_prize_code text,p_delta int,p_reason text,p_admin_user uuid) returns jsonb language plpgsql security definer set search_path=public as $$declare c campaigns;p prizes;avail int;mx int;ids uuid[];begin if p_delta=0 or abs(p_delta)>1000 then raise exception 'INVALID_DELTA';end if;if char_length(trim(p_reason))<3 then raise exception 'REASON_REQUIRED';end if;select * into c from campaigns where code=p_campaign for update;if not found then raise exception 'CAMPAIGN_NOT_FOUND';end if;select * into p from prizes where campaign_id=c.id and code=p_prize_code for update;if not found then raise exception 'PRIZE_NOT_FOUND';end if;if not exists(select 1 from admin_users where user_id=p_admin_user)then raise exception 'ADMIN_FORBIDDEN';end if;select count(*)::int into avail from prize_units where prize_id=p.id and status='AVAILABLE';if p_delta<0 and avail<abs(p_delta)then raise exception 'INSUFFICIENT_AVAILABLE_INVENTORY';end if;if p_delta>0 then select coalesce(max(unit_no),0)into mx from prize_units where campaign_id=c.id;insert into prize_units(campaign_id,prize_id,unit_no)select c.id,p.id,mx+x from generate_series(1,p_delta)x;else select array_agg(id)into ids from(select id from prize_units where prize_id=p.id and status='AVAILABLE'order by unit_no desc limit abs(p_delta)for update)q;delete from prize_units where id=any(ids);end if;update prizes set total_qty=total_qty+p_delta where id=p.id;update campaigns set total_inventory=total_inventory+p_delta where id=c.id;insert into inventory_adjustments(campaign_id,prize_id,admin_user_id,delta,reason)values(c.id,p.id,p_admin_user,p_delta,trim(p_reason));return jsonb_build_object('ok',true,'prize_code',p.code,'delta',p_delta,'available',avail+p_delta);end$$;
revoke all on function admin_dashboard(text),admin_list_spins(text,text,int,int),admin_adjust_inventory(text,text,int,text,uuid)from public,anon,authenticated;grant execute on function admin_dashboard(text),admin_list_spins(text,text,int,int),admin_adjust_inventory(text,text,int,text,uuid)to service_role;
