alter table campaigns add column if not exists inventory_version bigint not null default 1;
create index if not exists idx_spins_campaign_created on spins(campaign_id,created_at desc);
create index if not exists idx_spins_campaign_status on spins(campaign_id,status);
create index if not exists idx_prize_units_prize_status on prize_units(prize_id,status);
create index if not exists idx_inventory_adjustments_campaign_created on inventory_adjustments(campaign_id,created_at desc);

create or replace function admin_bootstrap(p_campaign text,p_page_size int default 25) returns jsonb language plpgsql security definer set search_path=public as $$declare d jsonb;s jsonb;begin select admin_dashboard(p_campaign)into d;select admin_list_spins(p_campaign,'',1,p_page_size)into s;return d||jsonb_build_object('spins',s);end$$;

create or replace function admin_adjust_inventory(p_campaign text,p_prize_code text,p_delta int,p_reason text,p_admin_user uuid) returns jsonb language plpgsql security definer set search_path=public as $$declare c campaigns;p prizes;avail int;mx int;ids uuid[];new_version bigint;begin if p_delta=0 or abs(p_delta)>1000 then raise exception 'INVALID_DELTA';end if;if char_length(trim(p_reason))<3 then raise exception 'REASON_REQUIRED';end if;select * into c from campaigns where code=p_campaign for update;if not found then raise exception 'CAMPAIGN_NOT_FOUND';end if;select * into p from prizes where campaign_id=c.id and code=p_prize_code for update;if not found then raise exception 'PRIZE_NOT_FOUND';end if;if not exists(select 1 from admin_users where user_id=p_admin_user)then raise exception 'ADMIN_FORBIDDEN';end if;select count(*)::int into avail from prize_units where prize_id=p.id and status='AVAILABLE';if p_delta<0 and avail<abs(p_delta)then raise exception 'INSUFFICIENT_AVAILABLE_INVENTORY';end if;if p_delta>0 then select coalesce(max(unit_no),0)into mx from prize_units where campaign_id=c.id;insert into prize_units(campaign_id,prize_id,unit_no)select c.id,p.id,mx+x from generate_series(1,p_delta)x;else select array_agg(id)into ids from(select id from prize_units where prize_id=p.id and status='AVAILABLE'order by unit_no desc limit abs(p_delta)for update)q;delete from prize_units where id=any(ids);end if;update prizes set total_qty=total_qty+p_delta where id=p.id;update campaigns set total_inventory=total_inventory+p_delta,inventory_version=inventory_version+1 where id=c.id returning inventory_version into new_version;insert into inventory_adjustments(campaign_id,prize_id,admin_user_id,delta,reason)values(c.id,p.id,p_admin_user,p_delta,trim(p_reason));return jsonb_build_object('ok',true,'prize_code',p.code,'delta',p_delta,'available',avail+p_delta,'total_qty',p.total_qty+p_delta,'inventory_version',new_version);end$$;
revoke all on function admin_bootstrap(text,int) from public,anon,authenticated;grant execute on function admin_bootstrap(text,int) to service_role;
